/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ComponentTest1 {
        /**
          * The text to show inside the button
         */
        "buttontext": string;
        /**
          * Could be a primary button, a secondary, etc
         */
        "buttontype": string;
    }
    interface MyComponentA {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLComponentTest1Element extends Components.ComponentTest1, HTMLStencilElement {
    }
    var HTMLComponentTest1Element: {
        prototype: HTMLComponentTest1Element;
        new (): HTMLComponentTest1Element;
    };
    interface HTMLMyComponentAElement extends Components.MyComponentA, HTMLStencilElement {
    }
    var HTMLMyComponentAElement: {
        prototype: HTMLMyComponentAElement;
        new (): HTMLMyComponentAElement;
    };
    interface HTMLElementTagNameMap {
        "component-test1": HTMLComponentTest1Element;
        "my-component-a": HTMLMyComponentAElement;
    }
}
declare namespace LocalJSX {
    interface ComponentTest1 {
        /**
          * The text to show inside the button
         */
        "buttontext"?: string;
        /**
          * Could be a primary button, a secondary, etc
         */
        "buttontype"?: string;
    }
    interface MyComponentA {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "component-test1": ComponentTest1;
        "my-component-a": MyComponentA;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "component-test1": LocalJSX.ComponentTest1 & JSXBase.HTMLAttributes<HTMLComponentTest1Element>;
            "my-component-a": LocalJSX.MyComponentA & JSXBase.HTMLAttributes<HTMLMyComponentAElement>;
        }
    }
}
